server:
  port: 8080
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: create
  data:
    mongodb:
      uri: mongodb://localhost:27017/taxi_rental_service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher